version: "3"
services:
  SeSePerson:
    build: .
    container_name: SeSePerson # 容器名称
    ports:
      - "8788:8788" # 映射端口到宿主机 宿主机端口:容器端口
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ~/.SeSePerson/data:/app/seseperson/database        # 这几条为挂载工作数据目录与配置文件
#      - ~/.SeSePerson/accounts:/app/seseperson/accounts   # 挂载格式为 宿主机路径:容器路径
      - ~/.SeSePerson/configs:/app/seseperson/configs      # 默认的工作路径为 ~/.seseperson 注意该目录默认状态下是隐藏的