ConfigVersion: "0.0.0"

BotConfig:
  host: "{host}"
  port: {port}
  debug: false
  superusers: {superusers}
  nickname: ["涩涩人", "SeSe", "SeSePerson"]
  command_start: ["/"]
  command_sep: ["."]
  session_expire_timeout: 60
  access_token: ""
  proxy: "{proxy}"
  request_timeout: 5